### ISSUE TITLE
Magnets not touching in SB Mount-rods 

### ISSUE THREAD

**Issue by jettoblack** [viesturz/TapChanger-lite#10]
As of revision b430098

I printed the new rods shuttle & SB plate and there is an issue with the magnets. When the shuttle is fully inserted into the SB plate as far as it can physically go (the top bearing "ears" of the shuttle are touching the optotap holder and the shuttle's optotap trigger is almost touching the little bump in optotap mount the plate), there is a ~ 2mm gap between the 2 magnets, they are not even close to touching, and so there is very little magnetic force. Some of it may be a print tolerance issue but I don't think that would add up to 2mm.  

I can fit an entire 2mm thick magnet in between the 2 magnets and the shuttle still fully inserts into the SB plate to the exact same end position that it does without the extra 2mm magnet. (and now you get that satisfying magnet click, so the gap seems to be right around 2mm)

I'm not sure if this is because the shuttle is not fully inserting into the mount as far as you expect because the bearing holders are hitting the optotap holder sooner than expected, but, it doesn't look like there is 2mm of clearance between the optotap trigger and the optotap holder, when there is still at least 2mm clearance between the 2 magnets.

I printed multiple copies of the shuttle & mount with different settings, different extrusion multipliers, etc. in case it was a printing error but they all show the same tolerance in this regard.

It's impossible to get a pic of this happening inside the printed part but I'll see if I can demonstrate it in fusion 360.

**Comment by viesturz** [comment]
The magnet holes are a bit deeper than before, I will fix that. But that
should bing them apart only about 1mm max.

The faces the magnets are in should be fully touching and there should be
about 0.5 mm gap between the plate going into optotap and it's opposite
protusion.
Perhaps the screws you are using for optotap are too long and interfering
with the bearing mounts?

I'm reprinting the latest design to test.

**Comment by viesturz** [comment]
Oh, shit, there is 0.7mm unnecessary gap on top of that. and 1.7mm in total. Fixing, the shuttle stays the same, the toolhead plate will change.

**Comment by viesturz** [comment]
Pushed an update and printing a test... Thanks again for spotting :D

**Comment by jettoblack** [comment]
@viesturz Great, I'll take a look tonight!

While you're at it, another suggestion (I can make this a separate issue if you prefer):

The bottom/back of the shuttle (belt side) has 45 degree cut outs on the 4 corners which makes the shuttle really difficult to print cleanly, even with supports, 100% part fan, and printing very slow, I can never get these overhangs to print without a lot of curling and warping.  How about getting rid of these cutouts, and extending the 4 corners down to the print bed (just maintain the center bolt hole all the way through)? It doesn't look like it will interfere with anything. The weight of the extra plastic will be minimal. What do you think?

Thanks again for the great design and all the hard work btw.

**Comment by viesturz** [comment]
Thats a neat idea, will play with it. I can see how 70 deg overhangs are
difficult.
 Those corners are not structural, so thinking about closing up the hole
and tapering half for it at a 45 degree angle and the extending to the
build plate.

**Comment by jettoblack** [comment]
@viesturz I'd keep the bolt holes all the way through if you can, I use a bolt through the back to help align the heatset before applying heat to get the angle just right.

One more thought.

Is there enough space for 2 magnets side-by-side? I had one incident where the nozzle hit a warped print and ejected the tool right off the shuttle. (Old plate-based design.) I don't know if 2 would have helped, but maybe. I only thought of it because Voron Tap uses 2-4 magnets, with 4 being optional and allowing higher acceleration, maybe 2 magnets would do the same here.

**Comment by viesturz** [comment]
Sure added a thru holes version.

Yes there is room for 2x2 magnets, but frankly it's unlikley that will help for seriously warped parts.
