### ISSUE TITLE
Tiny typo in README.md

### ISSUE THREAD

**Issue by mggevaer** [viesturz/TapChanger-lite#3]
Looks like you typed Foron instead of Voron

![image](https://github.com/viesturz/TapChanger-lite/assets/41551215/1f96c38b-dbf9-47f4-8c45-2b50a6314fbe)

(Thanks for working on and sharing this project, this is really cool! Especially the focus on simplifying and improving accessibility of the project with things like the TapChanger-lite)

**Comment by viesturz** [comment]
Haha, thanks, fixed.
